/**
 * Realistic demo trace showing a Claude Code session
 * that spawned 3 sub-agents for a feature implementation.
 */

import type { Trace, Decision, TokenUsage, CostBreakdown } from '@agenttrace/core';

function tok(input: number, output: number, cacheRead = 0): TokenUsage {
  return { input, output, cacheRead, cacheWrite: 0 };
}

function cost(tokens: number): CostBreakdown {
  return { tokens, tools: 0, total: tokens };
}

const now = Date.now();
const min = 60_000;

export const DEMO_TRACE: Trace = {
  id: 'trace-demo-001',
  sessionId: 'session-abc123',
  project: 'my-saas-app',
  startedAt: now - 12 * min,
  endedAt: now,
  model: 'claude-sonnet-4-6',
  provider: 'anthropic',
  tokens: tok(380_000, 45_000, 120_000),
  cost: cost(1.965),
  wasteTotal: 0.82,
  wastePercentage: 0.417,
  decisionCount: 23,
  agentCount: 4,
  rootDecision: {
    id: 'root',
    parentId: null,
    agentId: 'main',
    agentName: 'Orchestrator',
    type: 'reasoning',
    tool: null,
    description: 'Implement user authentication with OAuth',
    startedAt: now - 12 * min,
    endedAt: now,
    tokens: tok(40_000, 8_000, 30_000),
    cost: cost(0.24),
    outcome: 'success',
    wasteScore: 0,
    wasteReason: null,
    metadata: {},
    children: [
      // Agent 1: Research — explored too many files
      {
        id: 'span-1',
        parentId: 'root',
        agentId: 'agent-research',
        agentName: 'Research Agent',
        type: 'delegation',
        tool: 'Agent',
        description: 'Research existing auth patterns in codebase',
        startedAt: now - 11 * min,
        endedAt: now - 8 * min,
        tokens: tok(120_000, 12_000, 40_000),
        cost: cost(0.54),
        outcome: 'partial',
        wasteScore: 0.55,
        wasteReason: 'Read 34 files but only 3 were relevant to auth',
        metadata: {},
        children: [
          ...Array.from({ length: 8 }, (_, i): Decision => ({
            id: `span-1-read-${i}`,
            parentId: 'span-1',
            agentId: 'agent-research',
            agentName: 'Research Agent',
            type: 'exploration',
            tool: 'Read',
            description: `Read ${['package.json', 'tsconfig.json', 'README.md', 'src/utils/format.ts', 'src/utils/logger.ts', 'src/db/schema.ts', 'src/auth/middleware.ts', 'src/auth/providers.ts'][i]}`,
            startedAt: now - 11 * min + i * 20_000,
            endedAt: now - 11 * min + (i + 1) * 20_000,
            tokens: tok(8_000, 500),
            cost: cost(0.031),
            outcome: i >= 6 ? 'success' : 'dead_end',
            wasteScore: i >= 6 ? 0 : 0.9,
            wasteReason: i >= 6 ? null : 'File not related to authentication',
            children: [],
            metadata: {},
          })),
          {
            id: 'span-1-grep-1',
            parentId: 'span-1',
            agentId: 'agent-research',
            agentName: 'Research Agent',
            type: 'exploration',
            tool: 'Grep',
            description: 'Grep "auth" across codebase',
            startedAt: now - 9.5 * min,
            endedAt: now - 9.3 * min,
            tokens: tok(15_000, 2_000),
            cost: cost(0.075),
            outcome: 'success',
            wasteScore: 0,
            wasteReason: null,
            children: [],
            metadata: {},
          },
        ],
      },
      // Agent 2: Web research — first result had the answer
      {
        id: 'span-2',
        parentId: 'root',
        agentId: 'agent-docs',
        agentName: 'Docs Agent',
        type: 'delegation',
        tool: 'Agent',
        description: 'Research OAuth provider setup docs',
        startedAt: now - 8 * min,
        endedAt: now - 6 * min,
        tokens: tok(80_000, 8_000, 20_000),
        cost: cost(0.38),
        outcome: 'partial',
        wasteScore: 0.45,
        wasteReason: 'Answer was in first search result, but searched 4 more',
        metadata: {},
        children: [
          ...Array.from({ length: 5 }, (_, i): Decision => ({
            id: `span-2-web-${i}`,
            parentId: 'span-2',
            agentId: 'agent-docs',
            agentName: 'Docs Agent',
            type: 'exploration',
            tool: 'WebFetch',
            description: `Fetch ${['next-auth.js.org/docs', 'auth0.com/docs/quickstart', 'clerk.com/docs', 'supabase.com/docs/auth', 'firebase.google.com/docs/auth'][i]}`,
            startedAt: now - 8 * min + i * 25_000,
            endedAt: now - 8 * min + (i + 1) * 25_000,
            tokens: tok(12_000, 1_500),
            cost: cost(0.058),
            outcome: i === 0 ? 'success' : 'redundant',
            wasteScore: i === 0 ? 0 : 0.85,
            wasteReason: i === 0 ? null : 'Answer already found in first result',
            children: [],
            metadata: {},
          })),
        ],
      },
      // Agent 3: Implementation — wrote code, tests failed twice
      {
        id: 'span-3',
        parentId: 'root',
        agentId: 'agent-impl',
        agentName: 'Implementation Agent',
        type: 'delegation',
        tool: 'Agent',
        description: 'Implement OAuth middleware and routes',
        startedAt: now - 6 * min,
        endedAt: now - 1 * min,
        tokens: tok(140_000, 17_000, 30_000),
        cost: cost(0.675),
        outcome: 'success',
        wasteScore: 0.15,
        wasteReason: null,
        metadata: {},
        children: [
          {
            id: 'span-3-write-1',
            parentId: 'span-3',
            agentId: 'agent-impl',
            agentName: 'Implementation Agent',
            type: 'generation',
            tool: 'Write',
            description: 'Write src/auth/oauth.ts',
            startedAt: now - 5.5 * min,
            endedAt: now - 5 * min,
            tokens: tok(20_000, 4_000),
            cost: cost(0.12),
            outcome: 'success',
            wasteScore: 0,
            wasteReason: null,
            children: [],
            metadata: {},
          },
          {
            id: 'span-3-test-1',
            parentId: 'span-3',
            agentId: 'agent-impl',
            agentName: 'Implementation Agent',
            type: 'tool_call',
            tool: 'Bash',
            description: 'Bash: npm test -- --filter auth',
            startedAt: now - 4.8 * min,
            endedAt: now - 4.5 * min,
            tokens: tok(15_000, 2_000),
            cost: cost(0.075),
            outcome: 'failure',
            wasteScore: 0.6,
            wasteReason: 'Test failed: missing env variable OAUTH_SECRET',
            children: [],
            metadata: {},
          },
          {
            id: 'span-3-fix-1',
            parentId: 'span-3',
            agentId: 'agent-impl',
            agentName: 'Implementation Agent',
            type: 'generation',
            tool: 'Edit',
            description: 'Edit src/auth/oauth.ts — add env validation',
            startedAt: now - 4.3 * min,
            endedAt: now - 4 * min,
            tokens: tok(18_000, 3_000),
            cost: cost(0.105),
            outcome: 'success',
            wasteScore: 0,
            wasteReason: null,
            children: [],
            metadata: {},
          },
          {
            id: 'span-3-test-2',
            parentId: 'span-3',
            agentId: 'agent-impl',
            agentName: 'Implementation Agent',
            type: 'tool_call',
            tool: 'Bash',
            description: 'Bash: npm test -- --filter auth',
            startedAt: now - 3.8 * min,
            endedAt: now - 3.5 * min,
            tokens: tok(15_000, 2_000),
            cost: cost(0.075),
            outcome: 'failure',
            wasteScore: 0.6,
            wasteReason: 'Test failed: incorrect callback URL format',
            children: [],
            metadata: {},
          },
          {
            id: 'span-3-fix-2',
            parentId: 'span-3',
            agentId: 'agent-impl',
            agentName: 'Implementation Agent',
            type: 'generation',
            tool: 'Edit',
            description: 'Edit src/auth/oauth.ts — fix callback URL',
            startedAt: now - 3.3 * min,
            endedAt: now - 3 * min,
            tokens: tok(18_000, 3_000),
            cost: cost(0.105),
            outcome: 'success',
            wasteScore: 0,
            wasteReason: null,
            children: [],
            metadata: {},
          },
          {
            id: 'span-3-test-3',
            parentId: 'span-3',
            agentId: 'agent-impl',
            agentName: 'Implementation Agent',
            type: 'tool_call',
            tool: 'Bash',
            description: 'Bash: npm test -- --filter auth',
            startedAt: now - 2.8 * min,
            endedAt: now - 2.5 * min,
            tokens: tok(15_000, 2_000),
            cost: cost(0.075),
            outcome: 'success',
            wasteScore: 0,
            wasteReason: null,
            children: [],
            metadata: {},
          },
        ],
      },
      // Direct tool call by orchestrator
      {
        id: 'span-4',
        parentId: 'root',
        agentId: 'main',
        agentName: 'Orchestrator',
        type: 'generation',
        tool: 'Write',
        description: 'Write docs/auth-setup.md',
        startedAt: now - 1 * min,
        endedAt: now - 0.5 * min,
        tokens: tok(10_000, 3_000),
        cost: cost(0.075),
        outcome: 'success',
        wasteScore: 0,
        wasteReason: null,
        children: [],
        metadata: {},
      },
    ],
  },
  agents: [
    {
      id: 'main', name: 'Orchestrator', parentId: null, model: 'claude-sonnet-4-6',
      decisionCount: 2, tokens: tok(50_000, 11_000, 30_000), cost: cost(0.315),
      wasteTotal: 0, wastePercentage: 0, topWasteDecisions: [],
    },
    {
      id: 'agent-research', name: 'Research Agent', parentId: 'main', model: 'claude-sonnet-4-6',
      decisionCount: 10, tokens: tok(120_000, 12_000, 40_000), cost: cost(0.54),
      wasteTotal: 0.30, wastePercentage: 0.55,
      topWasteDecisions: [
        { decisionId: 'span-1-read-0', description: 'Read package.json', cost: 0.031, wasteScore: 0.9, wasteReason: 'Not related to auth' },
        { decisionId: 'span-1-read-1', description: 'Read tsconfig.json', cost: 0.031, wasteScore: 0.9, wasteReason: 'Not related to auth' },
      ],
    },
    {
      id: 'agent-docs', name: 'Docs Agent', parentId: 'main', model: 'claude-sonnet-4-6',
      decisionCount: 6, tokens: tok(80_000, 8_000, 20_000), cost: cost(0.38),
      wasteTotal: 0.20, wastePercentage: 0.45,
      topWasteDecisions: [
        { decisionId: 'span-2-web-1', description: 'Fetch auth0.com/docs', cost: 0.058, wasteScore: 0.85, wasteReason: 'Answer already found' },
      ],
    },
    {
      id: 'agent-impl', name: 'Implementation Agent', parentId: 'main', model: 'claude-sonnet-4-6',
      decisionCount: 7, tokens: tok(140_000, 17_000, 30_000), cost: cost(0.675),
      wasteTotal: 0.09, wastePercentage: 0.13,
      topWasteDecisions: [
        { decisionId: 'span-3-test-1', description: 'Test run (failed)', cost: 0.075, wasteScore: 0.6, wasteReason: 'Missing env variable' },
      ],
    },
  ],
  insights: [
    {
      id: 'insight-1', severity: 'warning', category: 'dead_end_exploration',
      title: 'Research Agent read 6 irrelevant files',
      description: 'The Research Agent explored 8 files but only 2 (auth/middleware.ts, auth/providers.ts) were relevant. Files like package.json, tsconfig.json, and utility modules were dead ends.',
      cost: 0.19, confidence: 0.85,
      evidence: ['6 of 8 file reads produced no auth-related information', 'Each dead-end cost >$0.03 with zero contribution to outcome'],
      affectedDecisions: ['span-1-read-0', 'span-1-read-1', 'span-1-read-2', 'span-1-read-3', 'span-1-read-4', 'span-1-read-5'],
      suggestion: 'Narrow the research scope: instruct the agent to focus on auth/ directory first, or provide file patterns.',
    },
    {
      id: 'insight-2', severity: 'warning', category: 'redundant_work',
      title: 'Docs Agent fetched 4 redundant pages',
      description: 'The first search result (next-auth.js.org) contained the needed OAuth setup guide, but the agent continued fetching 4 more provider docs unnecessarily.',
      cost: 0.23, confidence: 0.75,
      evidence: ['First result (next-auth.js.org) was used in implementation', '4 subsequent fetches produced no new information used downstream'],
      affectedDecisions: ['span-2-web-1', 'span-2-web-2', 'span-2-web-3', 'span-2-web-4'],
      suggestion: 'Add early-exit logic: if the first result answers the question, stop searching.',
    },
    {
      id: 'insight-3', severity: 'info', category: 'retry_loop',
      title: 'Implementation Agent: 2 test failures before pass',
      description: 'Tests failed twice due to missing env variable and incorrect callback URL. Both could have been caught with pre-validation.',
      cost: 0.15, confidence: 0.90,
      evidence: ['2 consecutive test failures with the same test command', 'Failures were env/config issues, not logic bugs — preventable with pre-checks'],
      affectedDecisions: ['span-3-test-1', 'span-3-test-2'],
      suggestion: 'Add environment validation before running tests. Check .env.example for required variables.',
    },
  ],
};
